# Database credentials

database_test:
  host: "20.106.201.244"
  port: "27018"
  user: "Mindy"
  pass: "QMRhLk9m8rqXWC3X9pMJ"
  dbname: "test02neofura"
  database: "test02neofura"

database_staging:
  host: "20.106.201.244"
  port: "27018"
  user: "Vincent"
  pass: "QMRhLk9m8rqXWC3X9pMJ"
  dbname: "neofura"
  database: "neofura"

database_local_test:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  pass: "root"
  database: "magnet"

database_local_staging:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  pass: "root"
  database: "main"






