version: "1.0"
services:
  megaoasis_filesystem:
    build:
      context: "./"
      args:
        RT: ${RUNTIME}
    ports:
      - "8080:8080"
    networks:
          - network
    restart: always
    container_name: megaoasis_filesystem_${RUNTIME}
    volumes:
      - ./logs:/go/application/Logs/
      - /opt/megaoasis-image/magnet/:/go/application/image/
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - network
    restart: always
    ports:
      - "6379:6379"
    container_name: megaoasis_filesystem_cache_${RUNTIME}

networks:
  network:


