version: "1.0"
services:
  megaoasis_filesystem:
    build:
      context: "./"
      args:
        RT: ${RUNTIME}
    ports:
      - "8080:8080"
    networks:
          - network
    restart: always
    container_name: megaoasis_filesystem_${RUNTIME}
    volumes:
      - ./logs:/go/application/Logs/
      - /opt/megaoasis-image/magnet/:/go/application/image/
networks:
  network: